### ISSUE TITLE
dividing by 3 ?

### ISSUE THREAD

**Issue by pcout** [boxlight/bl-jquery-image-center#1]
hi,

in your code (lines 50 to 54) you have:

$img.css({
      'position': 'absolute',
      'left':     Math.round((div.w - img.w) / 2),
      'top':      Math.round((div.h - img.h) / 3)
});

in the 'top' attribute you are dividing by 3. Why ? Shouldn´t you be dividing by 2 so the image centers in the middle ?

**Comment by rcambrj** [comment]
A portrait image will usually need centering a third of the way down rather than halfway. The thinking behind this is that the most important part of a person's face is in this area.

Although this works really well for us and we've never needed to change it, it could be a configurable setting...
