### ISSUE TITLE
onResize window

### ISSUE THREAD

**Issue by mylatestwork** [boxlight/bl-jquery-image-center#5]
Hi great script really useful,

how can i execute the script on resize the window and not onLoad.
i try something like…

window.onresize=function(){
  $('#imageCenterResize img').centerImage('inside');
    };
but didn´t work well!

**Comment by rcambrj** [comment]
Try

$(window).bind('resize', function() {
$('#imageCenterResize img').centerImage('inside');
});

**Comment by mylatestwork** [comment]
thx!
