### ISSUE TITLE
combine on resize, load, click…

### ISSUE THREAD

**Issue by mylatestwork** [boxlight/bl-jquery-image-center#6]
cool thx for the quick response! but now i have another problem the on resize don´t work with my slideshow maybe i need a combination of click, ready and resize… ? plz have a look at the slideshow: http://gbayerl.com/v2/index.php/singles/architecture/
on load it´s fine but on click (to the next image) the script don´t resize it to the parent div:
http://gbayerl.com/v2/index.php/singles/people/
i try something:

$(document).on('resize', function() { $('#slideshow img').centerImage('inside'); });

$('window').on('click', function() { $('#slideshow img').centerImage('inside'); });

$(window).on('ready', function() { $('#slideshow img').centerImage('inside'); });

so much events to choose here http://api.jquery.com/category/events/

**Comment by mylatestwork** [comment]
hi I solve the problem by myself :) but i got another issue my layout got an sticky menu and fixed footer how can i take off these 120px from the height so that the image fits in the layout without scrolling? i don't get it through css padding oder height changes so can i subtract it inside the js?

**Comment by rcambrj** [comment]
It's hard to advise without seeing the code. If you can provide a jsfiddle or similar I'll be able to help :)
