### ISSUE TITLE
Not working in Chrome and IE 9

### ISSUE THREAD

**Issue by cuga-cz** [boxlight/bl-jquery-image-center#7]
Hi,

please could you test it if everything is right, because I can see it working only in FF. Not in the latest Chrome and IE 9.

Thanks for reply

**Comment by jamiel** [comment]
This is resolved now on our test page:

http://boxlight.github.io/bl-jquery-image-center/

Github does not want people to use raw.github.com as a CDN which is what we were doing to serve the plugin. If you were getting the same bug in your code make sure you are not doing the same and reference the plugin relative to your project.

**Comment by cuga-cz** [comment]
Nice work! Thank you
