### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by dgtlmoon** [boxlight/bl-jquery-image-center#9]
Hi, so the image's are now missing when i use this plugin (after overcoming the 'fn undefined' issue, looks like theres some crazy padding pushing them off the page
![screen](https://f.cloud.github.com/assets/275001/867009/434904b8-f6cc-11e2-94e0-a9e230b4eb22.jpg)

**Comment by rcambrj** [comment]
Does `<div class="field-item even">` have a height?

If there is no height on that element, the plugin will most likely fail to work correctly.
